import { useEffect, useState } from "react"
import { Disclaimer, SectionCard } from "@/components/common"
import { AlertCard, VitalsGrid } from "@/components/doctor"
import { useDoctorLayout } from "@/layouts"
import { clinicalService } from "@/services"
import type { ClinicalAlert, VitalObservation } from "@/types"

export function AlertsPage() {
  const { patients, selectedPatientId } = useDoctorLayout()
  const [alerts, setAlerts] = useState<ClinicalAlert[]>([])
  const [vitals, setVitals] = useState<VitalObservation[]>([])
  const [loading, setLoading] = useState(true)

  const patient = patients.find((entry) => entry.id === selectedPatientId)

  useEffect(() => {
    let cancelled = false
    setLoading(true)

    Promise.all([
      clinicalService.getAlerts(selectedPatientId),
      clinicalService.getVitals(selectedPatientId),
    ])
      .then(([patientAlerts, patientVitals]) => {
        if (cancelled) return
        setAlerts(patientAlerts)
        setVitals(patientVitals)
      })
      .catch(() => {
        if (!cancelled) {
          setAlerts([])
          setVitals([])
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [selectedPatientId])

  const labAlerts = alerts.filter((alert) => alert.category === "lab")
  const otherAlerts = alerts.filter((alert) => alert.category !== "lab")

  return (
    <div className="p-4 flex flex-col gap-6 h-full overflow-y-auto sm:p-6">
      <div>
        <h2 className="text-xl font-bold text-[#0D1B2A] sm:text-2xl">
          Alerts &amp; Abnormal Values
        </h2>
        <p className="text-sm text-[#5A7184]">
          {patient ? `${patient.name} — ${patient.token} — ` : ""}For physician
          review only
        </p>
      </div>

      <Disclaimer tone="info">
        These flags are generated by Clinsutra AI to assist clinical
        decision-making. They are{" "}
        <strong>not autonomous diagnoses or prescriptions</strong>. All findings
        must be interpreted by a qualified physician in clinical context, and no
        treatment or dose is recommended here.
      </Disclaimer>

      {loading ? (
        <div className="flex flex-col gap-3" aria-busy="true">
          {[0, 1].map((index) => (
            <div key={index} className="h-28 rounded-2xl shimmer" />
          ))}
        </div>
      ) : (
        <>
          <div>
            <div className="text-sm font-bold text-[#0D1B2A] uppercase tracking-wider mb-3">
              🧪 Abnormal Laboratory Values
            </div>
            {labAlerts.length === 0 ? (
              <div className="bg-white border border-[#D1E4ED] rounded-2xl px-5 py-6 text-sm text-[#5A7184]">
                No laboratory values outside the reference range are on file.
              </div>
            ) : (
              <div className="flex flex-col gap-3">
                {labAlerts.map((alert) => (
                  <AlertCard key={alert.id} alert={alert} />
                ))}
              </div>
            )}
          </div>

          <div>
            <div className="text-sm font-bold text-[#0D1B2A] uppercase tracking-wider mb-3">
              💊 Medication &amp; Allergy Flags
            </div>
            {otherAlerts.length === 0 ? (
              <div className="bg-white border border-[#D1E4ED] rounded-2xl px-5 py-6 text-sm text-[#5A7184]">
                No medication or allergy flags for this patient.
              </div>
            ) : (
              <div className="flex flex-col gap-3">
                {otherAlerts.map((alert) => (
                  <AlertCard key={alert.id} alert={alert} />
                ))}
              </div>
            )}
          </div>

          <SectionCard title="Vital Signs at Kiosk (Self-reported)" icon="❤️">
            <VitalsGrid vitals={vitals} />
            <p className="text-xs text-[#5A7184] mt-3">
              ⚕ Self-reported by the patient during the kiosk interaction. Confirm
              with clinical measurement.
            </p>
          </SectionCard>
        </>
      )}
    </div>
  )
}
