"""initial schema

Revision ID: d223b55f7e73
Revises: 
Create Date: 2026-09-06 20:18:45.983042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223b55f7e73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('room', sa.String(length=32), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.Column('abha', sa.String(length=64), nullable=False),
    sa.Column('identification_mode', sa.Enum('abha', 'scan', 'new', name='identification_mode'), nullable=False),
    sa.Column('hospital_reg_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('Waiting', 'In Consultation', 'Completed', name='patient_status'), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('red_flag', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_token'), 'patients', ['token'], unique=True)
    op.create_table('clinical_alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('lab', 'interaction', 'caution', 'allergy', name='alert_category'), nullable=False),
    sa.Column('severity', sa.Enum('high', 'moderate', 'low', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('HIGH', 'LOW', name='alert_status'), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_alerts_patient_id'), 'clinical_alerts', ['patient_id'], unique=False)
    op.create_table('clinical_histories',
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('history_of_present_illness', sa.Text(), nullable=False),
    sa.Column('past_medical_history', sa.Text(), nullable=False),
    sa.Column('past_surgical_history', sa.Text(), nullable=False),
    sa.Column('family_history', sa.Text(), nullable=False),
    sa.Column('personal_history', sa.Text(), nullable=False),
    sa.Column('review_of_systems', sa.Text(), nullable=False),
    sa.Column('investigations_summary', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_clinician', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('document_session_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('doc_type', sa.Enum('prescription', 'lab', 'discharge', 'imaging', 'other', name='document_type'), nullable=False),
    sa.Column('stage', sa.Enum('queued', 'uploading', 'ocr', 'extracting', 'structuring', 'complete', 'failed', name='processing_stage'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('detected_type', sa.Enum('prescription', 'lab', 'discharge', 'imaging', 'other', name='detected_document_type'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_session_id'), 'documents', ['document_session_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('complaint_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('sort_key', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('Lab Report', 'Prescription', 'Hospital Visit', 'Diagnosis', 'Surgery', name='timeline_event_type'), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('color', sa.Enum('blue', 'green', 'orange', 'gray', 'red', name='timeline_color'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('abnormal', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_patient_id'), 'timeline_events', ['patient_id'], unique=False)
    op.create_table('vital_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('normal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_observations_patient_id'), 'vital_observations', ['patient_id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('substance', sa.String(length=200), nullable=False),
    sa.Column('reaction', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('high', 'moderate', 'low', name='allergy_severity'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['clinical_histories.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_extraction_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('option_ids', sa.JSON(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['clinical_histories.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Hand-adjusted from the autogenerated version: on MySQL/MariaDB, dropping
    an index that a FOREIGN KEY still depends on fails (error 1553).
    `DROP TABLE` removes its indexes on its own, so the explicit
    `op.drop_index(...)` calls autogenerate produced are simply omitted —
    tables are dropped children-first instead.
    """
    op.drop_table('medications')
    op.drop_table('interview_answers')
    op.drop_table('document_extraction_fields')
    op.drop_table('allergies')
    op.drop_table('vital_observations')
    op.drop_table('timeline_events')
    op.drop_table('interviews')
    op.drop_table('documents')
    op.drop_table('clinical_histories')
    op.drop_table('clinical_alerts')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
